language: c
sudo: true

before_install:
- sudo apt-get update
- sudo apt-get -y install wget
- sudo apt-get -y install unzip

env:
- BUILD_FLAGS=--disable-yasm
- BUILD_FLAGS=--disable-swscale
- BUILD_FLAGS=--disable-avfilter
- BUILD_FLAGS=--disable-decoder=h264
- BUILD_FLAGS=--disable-encoder=h264

script:
- ./configure --disable-yasm --disable-swscale --disable-avfilter --disable-decoder=h264 --disable-encoder=h264
- make complete
